[package]
name = "kingslayer"
version = "0.5.6"
authors = ["Maxwell Anderson <zaechus@proton.me>"]
edition = "2021"
license = "MIT"
description = "A text adventure dungeon crawler game written in Rust"
exclude = [".github"]
readme = "README.md"
repository = "https://github.com/Zaechus/kingslayer"
keywords = ["text", "adventure", "game", "dungeon", "crawler"]
categories = ["games", "game-engines"]

[dependencies]
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
ron = "0.7"

[lib]
crate-type = ["rlib"]

[profile.release]
strip = true